# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.processor.crap:
        class: AppBundle\Processor\CrapProcessor
        arguments:
            - "@event_dispatcher"

    app.event.subscriber.shitty:
        class: AppBundle\Event\Subscriber\ShittyEventSubscriber
        tags:
            - {name: kernel.event_subscriber}
